version: '3.8'

services:
  opease-frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      # Mount source code for hot reloading
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./vite.config.ts:/app/vite.config.ts
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.node.json:/app/tsconfig.node.json
      # Exclude node_modules and dist to avoid conflicts
      - /app/node_modules
      - /app/dist
    environment:
      - NODE_ENV=development
      - VITE_DEV_SERVER_HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    networks:
      - opease-dev-network

  # Optional: Backend service for API calls
  # Uncomment if you have a backend service
  # backend:
  #   image: your-backend-image
  #   ports:
  #     - "3333:3333"
  #   environment:
  #     - NODE_ENV=development
  #   networks:
  #     - opease-dev-network

networks:
  opease-dev-network:
    driver: bridge

volumes:
  node_modules:
