services:
  # Main API Service
  api:
    env_file:
      - .env.development
    build:
      context: .
      dockerfile: ${DOCKERFILE_API:-Dockerfile.api}
    container_name: spotx-api-dev
    ports:
      - "${API_EXTERNAL_PORT:-3333}:${PORT:-3333}" # this may need to be the other way around. 
    environment:
      - NODE_ENV=development
      - PORT=${PORT:-3333}
      - DATABASE_URL=postgresql://spotx_user:secure_password_2024@postgres:5432/spotx_db
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_key_here}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-7d}
    volumes:
      # Mount source code for development hot reloading
      - ./src:/app/src:ro
      # Mount Prisma schema for development
      - ./prisma:/app/prisma:ro
      # Mount package files for dependency checking
      - ./package.json:/app/package.json:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
      # Anonymous volume to preserve container's node_modules
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - spotx-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-3333}/health"] # this may need to be the other way around. 
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # PostgreSQL Database (Custom Build)
  postgres:
    env_file:
      - .env.development
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: spotx-postgres-dev
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-spotx_db}
      - POSTGRES_USER=${POSTGRES_USER:-spotx_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-secure_password_2024}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      # Persistent data storage for PostgreSQL
      - spotx_postgres_data:/var/lib/postgresql/data
      # Mount initialization script (read-only)
      - ./config/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    restart: unless-stopped
    networks:
      - spotx-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U spotx_user -d spotx_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'

  # pgAdmin for PostgreSQL Management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: spotx-pgadmin-dev
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@spotx.app
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
      PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED: 'False'
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: 'False'
    volumes:
      - spotx_pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - spotx-network

networks:
  spotx-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  spotx_postgres_data:
    driver: local
  spotx_pgadmin_data:
    driver: local 
